### PR TITLE
Updated Turkish Translation

### PR DESCRIPTION
**Pull request by tp-duolingo**
I have rewrited all of the previous Turkish translation and made it more user-friendly and understandable.

### CODE REVIEW

**Comment by iamdeka** [comment]
another-one-another-one-bites-the-dust

**Comment by tp-duolingo** [comment]
> another-one-another-one-bites-the-dust [ another-one-another-one-bites-the-dust ](https://private-user-images.githubusercontent.com/125897541/352681942-4e14e1d2-3701-4bc4-82a3-5e19b83e7779.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMzU3NjgsIm5iZiI6MTcyMjAzNTQ2OCwicGF0aCI6Ii8xMjU4OTc1NDEvMzUyNjgxOTQyLTRlMTRlMWQyLTM3MDEtNGJjNC04MmEzLTVlMTliODNlNzc3OS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQyMzExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmVlNjMyMThmZjM4ZTI4NjhlNDY1MDI1OGNhM2YwMmY4NzExN2ZmY2VhMGZmMmEyNWQyODNmNzg2Y2U1NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V43ifBFtVRILDGwYM1KRT3f98JG_l-U1tydpF0-5vXw) [ ](https://private-user-images.githubusercontent.com/125897541/352681942-4e14e1d2-3701-4bc4-82a3-5e19b83e7779.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMzU3NjgsIm5iZiI6MTcyMjAzNTQ2OCwicGF0aCI6Ii8xMjU4OTc1NDEvMzUyNjgxOTQyLTRlMTRlMWQyLTM3MDEtNGJjNC04MmEzLTVlMTliODNlNzc3OS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQyMzExMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmVlNjMyMThmZjM4ZTI4NjhlNDY1MDI1OGNhM2YwMmY4NzExN2ZmY2VhMGZmMmEyNWQyODNmNzg2Y2U1NzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V43ifBFtVRILDGwYM1KRT3f98JG_l-U1tydpF0-5vXw)

real

**Comment by tp-duolingo** [comment]
When review translations :blehbusiness:

**Comment by iamdeka** [comment]
#31

**Comment by tp-duolingo** [comment]
When 🙏🙏🙏🙏
At least use Crowdin 😔

**Pull request closed without merging**
